# generated by datamodel-codegen:
#   filename:  screening
#   timestamp: 2023-11-19T08:03:28+00:00

from __future__ import annotations

from typing import Any, List, Union

from pydantic import BaseModel, Field


class AdpExecutionStack(BaseModel):
    field_1: str = Field(..., alias='1')


class Strategy(BaseModel):
    pending: str
    running: str
    completed: str


class StatusHistory(BaseModel):
    strategy: Strategy


class FQDN(BaseModel):
    strategy: str


class AngularRange(BaseModel):
    strategy: None


class AdpStatus(BaseModel):
    strategy: str


class AdpInfo(BaseModel):
    strategy: str


class Strategy1(BaseModel):
    description: str
    omega: float
    chi: float
    phi: float
    totalRange: float
    multiplicity: float
    completeness: float
    anomalous_completness: float


class StrategyParams(BaseModel):
    spaceGroupNumber: str
    spaceGroupLabel: str
    a: float
    b: float
    c: float
    alpha: float
    beta: float
    gamma: float
    mosaicity: float
    highResolution: float


class Result(BaseModel):
    strategy: Strategy1
    strategy_params: StrategyParams


class Metadatum(BaseModel):
    name: str
    value: Union[List[Any], float, str]


class Model(BaseModel):
    field_id: str = Field(..., alias='_id')
    userAccount: str
    user: str
    uid: int
    gid: int
    createdOn: str
    lastUpdated: str
    beamline: str
    trackingId: str
    method: str
    beamTransmission: float
    beam_position_x: float
    beam_position_y: float
    detectorDistance: float
    exposureTime: float
    folder: str
    root_folder: str
    numFramesTotal: int
    datasetNo: int
    numberOfExpectedDatasets: int
    oscillationAngle: float
    prefix: str
    runNumber: int
    wavelength: float
    adpExecutionStack: AdpExecutionStack
    statusHistory: StatusHistory
    FQDN: FQDN
    angularRange: AngularRange
    adpStatus: AdpStatus
    adpInfo: AdpInfo
    result: Result
    detector: str
    roi: str
    mergeFolder: None
    mergeId: str
    seen: bool
    datasets_id: None
    metadata: List[Metadatum]
