# generated by datamodel-codegen:
#   filename:  standard
#   timestamp: 2023-11-19T08:07:19+00:00

from __future__ import annotations

from typing import Any, List, Union

from pydantic import BaseModel, Field
from pydantic_models.Adp.adpexecutionstack import AdpExecutionStack
from pydantic_models.Adp.fastxds import (Autoproc, StatusHistoryBase, FQDNBase, AngularRangeBase, AdpStatusBase, AdpInfoBase)
from pydantic_models.Adp.xdsinputparams import FastXds2Item, FastXds3Item, FastXds3Params

class StatusHistory(StatusHistoryBase):
    autoproc: Autoproc


class FQDN(FQDNBase):
    autoproc: str


class AngularRange(AngularRangeBase):
    autoproc: float


class AdpStatus(AdpStatusBase):
    autoproc: str


class AdpInfo(AdpInfoBase):
    autoproc: str



class AutoprocItem(BaseModel):
    order: str
    low_resolution_limit: float
    resolution_limit: float
    r_factor_observed: float
    rmeas_within: float
    rmeas: float
    rpim_within: float
    rpim: float
    observed_reflections: int
    unique_reflections: int
    Isigma: float
    completeness: float
    multiplicity: float
    cc_half: float
    anomalous_completeness: float
    anomalous_multiplicity: float
    anomalous_correlation: float
    sigAno: float


class SpacegroupItem(BaseModel):
    order: Union[int, str]
    sg: str
    sg_nr: int
    LGconfidence: Union[float, str]
    SGconfidence: Union[float, str]


class TableStaraniso1Item(BaseModel):
    order: str
    resolution: str
    matrix_1: str
    matrix_2: str
    matrix_3: str
    vectors: str


class TableStaraniso2Item(BaseModel):
    order: str
    low_resolution_limit: float
    resolution_limit: float
    r_factor_observed: float
    rmeas_within: float
    rmeas: float
    rpim_within: float
    rpim: float
    observed_reflections: int
    unique_reflections: int
    Isigma: float
    completeness: float
    completeness_ellipsoidal: float
    multiplicity: float
    cc_half: float
    anomalous_completeness: float
    anomalous_completeness_ellipsoidal: float
    anomalous_multiplicity: float
    anomalous_correlation: float
    sigAno: float


class AutoprocParams(BaseModel):
    command: str
    spaceGroupNumber: int
    spaceGroupLabel: str
    a: float
    b: float
    c: float
    alpha: float
    beta: float
    gamma: float
    mosaicity: float
    isa: float
    wilsonBfactor: float
    spacegroup_pointless: str
    spacegroup: List[SpacegroupItem]
    table_staraniso_1: List[TableStaraniso1Item]
    table_staraniso_2: List[TableStaraniso2Item]


class Result(BaseModel):
    fast_xds_2: List[FastXds2Item]
    fast_xds_3: List[FastXds3Item]
    fast_xds_3_params: FastXds3Params
    autoproc: List[AutoprocItem]
    autoproc_params: AutoprocParams
    fast_xds_1: List
    fast_xds_1_params: List
    fast_xds_2_params: List


class Metadatum(BaseModel):
    name: str
    value: Union[List[Any], float, str]


class Model(BaseModel):
    field_id: str = Field(..., alias='_id')
    userAccount: str
    user: str
    uid: int
    gid: int
    createdOn: str
    lastUpdated: str
    beamline: str
    trackingId: str
    method: str
    beamTransmission: float
    beam_position_x: float
    beam_position_y: float
    detectorDistance: float
    exposureTime: float
    folder: str
    root_folder: str
    numFramesTotal: int
    datasetNo: int
    numberOfExpectedDatasets: int
    oscillationAngle: float
    prefix: str
    runNumber: int
    wavelength: float
    adpExecutionStack: AdpExecutionStack
    statusHistory: StatusHistory
    FQDN: FQDN
    angularRange: AngularRange
    adpStatus: AdpStatus
    adpInfo: AdpInfo
    result: Result
    detector: str
    roi: str
    mergeFolder: str
    mergeId: str
    seen: bool
    datasets_id: None
    metadata: List[Metadatum]
